#config
CLIENTE_A_IP = '127.0.0.1'
CLIENTE_A_PORTA = 5000
CLIENTE_B_IP = '127.0.0.1'
CLIENTE_B_PORTA = 5001
SERVIDOR_IP = '127.0.0.1'
SERVIDOR_PORTA = 6000
ROTEADOR_IP = '127.0.0.1'
ROTEADOR_PORTA = 7000

VIP_CLIENTE_A = "CLIENTE_A"
VIP_CLIENTE_B = "CLIENTE_B"
VIP_SERVIDOR = "SERVIDOR_CENTRAL"

MAC_CLIENTE_A = "AA:BB:CC:DD:EE:01"
MAC_CLIENTE_B = "AA:BB:CC:DD:EE:03"
MAC_SERVIDOR = "AA:BB:CC:DD:EE:02"
MAC_ROTEADOR = "AA:BB:CC:DD:EE:FF"

TIMEOUT_SEGUNDOS = 4
MAX_TENTATIVAS = 5
TTL_INICIAL = 5