#config.py - configuracoes do projeto

#enderecos e portas
CLIENTE_IP = '127.0.0.1'
CLIENTE_PORTA = 5000
SERVIDOR_IP = '127.0.0.1'
SERVIDOR_PORTA = 6000
ROTEADOR_IP = '127.0.0.1'
ROTEADOR_PORTA = 7000

VIP_CLIENTE = "CLIENTE_1"
VIP_SERVIDOR = "SERVIDOR_PRINCIPAL"

MAC_CLIENTE = "AA:BB:CC:DD:EE:01"
MAC_SERVIDOR = "AA:BB:CC:DD:EE:02"
MAC_ROTEADOR = "AA:BB:CC:DD:EE:FF"

TIMEOUT_SEGUNDOS = 3
MAX_TENTATIVAS = 5

TTL_INICIAL = 5